### ISSUE TITLE
Gebruik const in plaats van var

### ISSUE THREAD

**Issue by Knetters** [zoepje/fix-the-flow-interactive-website#6]
Je kan beter const (constant) gebruiken voor variables die niet veranderen. Als het wel veranderd kan je let gebruiken.

**Comment by zoepje** [comment]
https://github.com/zoepje/fix-the-flow-interactive-website/blob/e164afa6c5957d882bf885dd3035f9d90ea5355f/scripts/script.js#L1-L3

Heb het veranderd.
